### ISSUE TITLE
Can you tell me more detailed instructions on how to use it?

### ISSUE THREAD

**Issue by ghost** [albatror/Updater#1]
I am a beginner who has just started using kvm.
Can you please tell me in detail where and how to do this?

**Comment by ghost** [comment]
My Discord is kakao112

I would be really happy if you could take a moment to explain.

**Comment by albatror** [comment]
This updater is maded for update the offsets of apex legends.
Get the offsets.ini from pastebin on https://www.unknowncheats.me/forum/apex-legends/319804-apex-legends-reversal-structs-offsets.html or extract it yourself from the game, put the file on the same folder, so you will have : 

- updater.py
- offsets.ini
- offsets.h (default one from a repo)

then execute this command : **py updater.py offsets.h offsets.ini**

updater.py will populate the offsets.h with the offsets.ini values.
It will write on the cmd/powershell windows wich ones need a manually update.

In the updated offsets.h file, you will be able to see on the updated offsets the date of the day you executed the updater.py script.
If some offsets have a later date, it's because they haven't been updated and probably need to be done manually (some don't need to be changed, it depends on changes in the game code).

When come back home, i will update the lastest offsets.ini file and update too the offsets.h on the repo then by this way it will be more clear.
